### ISSUE TITLE
Secret Ape #594[Issue]

### ISSUE THREAD

**Issue by BlokChn** [StashhApp/Stashh#4]
### Reproduction Steps

Secret Ape #594 is not showing me as the owner, but I am.

How to resolve?

### Issue

Secret Ape #594 is not showing me as the owner, but I am.

How to resolve?

### Expected Behavior

Secret Ape #594 is not showing me as the owner, but I am.

How to resolve?

### Reproducibility

Yes, every time

### Browser

Chrome

**Comment by scarylooking** [comment]
Please contact us directly on Discord or via Twitter. We can't offer support via GitHub
